xmtp/xmtp-dot-org

vision/roadmap.md

Also adds Read More links where there are relevant public GitHub issues/discussions.

Add Conversation Filtering to In Progress

---

src/components/MainContent/index.js

Fixed video showing play button after it's already clicked to play the video

Fix safari video showing play button twice

---

src/components/MainContent/index.js
src/css/tailwind.css
src/pages/index.js
src/theme/Footer/index.js

Fixed header width for homepage and documentation pages, they had different padding values on them for different pages
Fixed build-xmtp images loading both color mode images after reload.

Fix #175 and remove padding from elements

---

vision/roadmap.md

Updated to reflect WIP and recent deliveries as of Dec '22.

Update roadmap for Dec '22

---

src/components/BuiltWithXmtp/index.js

fix dark mode description

---

vision/roadmap.md

Changes in-line with our Mobile SDK announcement tomorrow

reorganized content, added phase definitions, improved readability

---

src/components/CardList/index.js

Thank you to @richardhuaaa for catching this typo and taking the time to report it to me!

Fix typo on SDKs and tools page

---

src/components/CardList/index.js

xmtp.chat is moved to BWX page

removed xmtp.chat, light re-phrasing

---

docs/client-sdk/javascript/tutorials/quickstart.md

- Update quickstart with new content added to xmtp-js README

Update xmtp-js quickstart tutorial

---

algolia.config.json

- Add blog URLs to Algolia config
- Add Built with XMTP URL to Algolia config

Add blog URLs to algolia search config

---

blog/eth-nyc-awards-2022.md

- Do this for one blog post to test. Then do all the rest.

Add unfurl image for a blog post

---

community/grants.md
vision/roadmap.md

Grants page update

---

docs/dev-concepts/faq.md

Brings the documentation of Waku usage up to date

updated waku usage

---

docs/dev-concepts/faq.md

Update per this feedback in Discord: https://discord.com/channels/831836269558235136/993229186951028796/1070632849994154015

Update rate limit info in FAQ

---

docusaurus.config.js

https://plausible.io/docs/outbound-link-click-tracking

Add support for Plausible outbound link clicks tracking

---

algolia.config.json
docs/client-sdk/dart/reference/overview.md
docusaurus.config.js

- Also some footer housekeeping

Add new SDK docs to Algolia index

---

docs/client-sdk/dart/tutorials/quickstart.md

- Add interoperable inbox info

Update link to reference docs in quickstart to use a callout

---

docs/dev-concepts/start-building.md

Update "Start building"

---

docs/dev-concepts/start-building.md

"0x0" gets automatically converted to "0×0". Put 0x address in code format as a temp workaround.

Fix 0x addresses

---

docs/client-sdk/javascript/concepts/intro-to-sdk.mdx
docs/dev-concepts/algorithms-in-use.mdx
docs/dev-concepts/architectural-overview.md
docs/dev-concepts/xips.mdx
src/pages/sdks-and-tools.mdx

In preparation for launch of sitewide feedback widget...

Remove manually inserted feedback links

---

docs/client-sdk/react/tutorials/quickstart.md

Based on React SDK PR 32, which refactors the useMessages hook and re-export items from the JS SDK

Update React SDK README

---

docs/dev-concepts/faq.md
vision/roadmap.md

Also updating FAQ about message attachments!

Add message deletion/editing to the FAQ and Roadmap

---

docs/use-cases/commerce.mdx
docs/use-cases/deso.mdx
docs/use-cases/finance.mdx
docs/use-cases/marketing.mdx
docs/use-cases/messaging.mdx

Updates from Yash and Daria. Some quick spelling/grammar fixes.

Fixes to use case pages

---

docs/use-cases/deso.mdx
docusaurus.config.js
src/components/Use-cases/index.js

Per discussion with Fabri, let's switch from using the "DeSo" use case language to "Web3 social" - which is friendlier and more immediately recognizable.

Change DeSo to web3 social

---

src/components/MainContent/index.js

Update to reflect the broader range of devs now building with XMTP

Update Join a community of builders module

---

vercel.json

Added header

---

docs/tutorials/identity-resolution.md
docs/tutorials/query-xmtp.md

Updates to the resolution docs about Lens v2 update using Airstack.
```
{
"lens": ["lens/@shanemac", "lens/@vitalik"]
} 
```

Airstack Lensv2 Resolution Update

---

src/components/BuiltWithXmtp/ListOfDevs.json

- [Preview](https://junk-range-possible-git-partnerorder-xmtp-labs.vercel.app/built-with-xmtp)

Re order of Apps icons

---

docs/faq.md

Improvements to our FAQ's based on AI feedback
- [Group chats](https://junk-range-possible-git-aiimprovements-xmtp-labs.vercel.app/docs/faq#group-chats)
- [Smart contract wallets](https://junk-range-possible-git-aiimprovements-xmtp-labs.vercel.app/docs/faq#does-xmtp-works-with-smart-contract-wallets)

FAQ Improvements

---

docs/faq.md

[Preview link](https://junk-range-possible-git-faq-network-xmtp-labs.vercel.app/docs/faq#is-the-xmtp-network-decentralized)
Update based on XMTP network compliance with Office of Foreign Assets Control (OFAC) sanctions and Committee on Foreign Investment in the United States (CFIUS) export compliance regulations.

Update network FAQ

---

docusaurus.config.js

Remove defer tag to resolve Flickity race condition.

Remove defer tag

---

docs/concepts/architectural-overview.md
docs/faq.md

Updated [resource](https://community.xmtp.org/t/decentralizing-xmtp-a-minimum-viable-proposal/510) about decentralization.

Updated resource about decentralization. 

---

docs/build/messages/remote-attachment.mdx

Updated to remove code snippets from external tools.

Updated attachment documentation

---

docs/build/user-consent.md

Updated consent docs based on latest flutter [PR](https://github.com/xmtp/xmtp-flutter/pull/94)
- [Preview](https://junk-range-possible-git-flutterconsent-xmtp-labs.vercel.app/docs/build/user-consent)

Flutter Consent Docs

---

blog/everyname-resolution.md
blog/trivia.md
docs/faq.md
docs/get-featured.md
docs/introduction.mdx
docs/tutorials/identity-resolution.md

Remove `prxshant.eth` references from the Docs

Remove Prxshant.eth References

---

docs/build/frames.md
docs/tutorials/frames.md

- [Preview](https://junk-range-possible-git-frames-xmtp-labs.vercel.app/docs/build/frames)

XMTP Frames Doc

---

docs/build/frames.md

This is totally my fault. The Open Frames specs have been a bit of a moving target, and these two properties changed in the last few days. Updated the documentation to be in line with where we are going.

Update Frames docs

---

docs/tutorials/identity-resolution.md

This is in response to issue 658 from SimpleHash.
Resolves #658.

Adding SimpleHash - Issue 658

---

docusaurus.config.js

Changed to `https://paragraph.xyz/@xmtp_community/`

Newsletter Fix

---

docs/v3/signature_changes.md

Quick update on the signature page based on Rich's feedback.

Updates on Signature FAQ based on feedback

---

docs/build/get-started/examples.md
docs/build/group-chat.md
docs/hackathons.mdx

ETH Denver Updates
- [ETH Denver](https://junk-range-possible-git-ethdenverv3-xmtp-labs.vercel.app/docs/hackathons)
- [Group Chat](https://junk-range-possible-git-ethdenverv3-xmtp-labs.vercel.app/docs/tutorials/group-chat-rn)
- [Examples](https://xmtp.org/docs/build/get-started/examples)

ETH Denver Updates

---

docs/hackathons.mdx

Denver Updates

---

docs/hackathons.mdx

Fix eth denver frames link

---

docs/hackathons.mdx

Update External Links

---

docs/build/messages/messages.md

Fix [snippet](https://junk-range-possible-git-codecforfix-xmtp-labs.vercel.app/docs/build/messages/) based on this [issue](https://github.com/xmtp/xmtp-web/issues/206)

codecFor fix in React

---

docs/hackathons.mdx

Remove ETH Denver References

---

docs/build/frames.md

Fix Frames [Doc](https://junk-range-possible-git-fixframesdoc-xmtp-labs.vercel.app/docs/build/frames) Links

Fix Frames Doc Links

---

docs/build/messages/remote-attachment.mdx

- [Preview](https://junk-range-possible-git-remoteflutter-xmtp-labs.vercel.app/docs/build/messages/remote-attachment?sdk=dart)

Remote Attachments in Flutter

---

docs/build/frames.md
docs/build/user-consent.md
docs/hackathons.mdx
docs/tutorials/portable-consent/_category_.json
docs/tutorials/render-frames.md
static/js/myjs.js

- [Chat Frames](https://junk-range-possible-git-framesdocs-xmtp-labs.vercel.app/docs/build/frames)

Frames Hackathon Update

---

docs/hackathons.mdx

Hackathon update

---

docs/tutorials/broadcast.md
static/js/myjs.js

Update broadcast [tutorial](https://junk-range-possible-git-broadcasttutorial-xmtp-labs.vercel.app/docs/tutorials/broadcast) with rate-limiting handling strategies. 
Based on the [repo](https://github.com/alexrisch/broadcaster-app) by @alexrisch

Update broadcast tutorial

---

docs/tutorials/broadcast.md
static/js/myjs.js

Revert "Update broadcast tutorial"

---

docs/build/frames.md
docs/build/notifications/react-native.md

Updating [Frames](https://xmtp.org/docs/build/frames)

Frames update

---

docusaurus.config.js
src/css/tailwind.css
src/pages/index.mdx
src/theme/Footer/index.js

- Remove bottom footer
- Increase footer text line height esp for wrapped text in mobile view
- Reduce footer top and bottom padding
- Add Socials column
- Add Site column for copyright and site policies
- Update home page meta description text

Reduce footer height

---

docs/build/frames.md
docs/tutorials/transaction-frames.md

Transaction Frame [Tutorial](https://junk-range-possible-git-txframes-xmtp-labs.vercel.app/docs/tutorials/transaction-frames)

Transaction Frame Tutorial

---

docs/faq.md

With so many false listings about XMTP tokens on the web, I thought it would be useful to provide an explicit statement on .org that there is no XMTP token.

Add FAQ about no XMTP token

---

docs/tutorials/transaction-frames.md

This PR adds logic needed to make an existing transaction frame work with smart contracts, e.g. in a mint scenario. 
Since most of the logic here overlaps with a basic tx frame, I just weaved it into this existing documentation — but let me know if a more separated out approach is preferred.

Add mint updates to tx documentation

---

docs/awesome.md

XMTP Awesome

---

docs/tutorials/subscribe-frames.md
docs/tutorials/transaction-frames.md

Documentation for the subscribe flow and some edits for the original transaction documentation.

Subscribe frame docs

---

docs/build/group-chat.md
docs/concepts/v3/group-chat.md

- Remove "Creator Only" permission option per Cameron

Add group chat membership section, update permissions concept

---

docs/build/get-started/examples.md

Content type Quickstarts

---

docs/build/group-chat.md
docs/build/streams.md

Make <Tabs groupId="sdk-langs"> values consistent so selected tab remains selected across relevant pages. Still needs some work.

Tab name fix

---

docs/build/group-chat.md
docs/build/messages/custom.mdx
docs/build/messages/reply.mdx

* Updated imports in Reply and custom content type docs
* Updated node code samples for group chats
Prettier also adjusted some formatting.

Update various docs

---

src/theme/NotFound.js

Add custom 404 page that provides users with actions they can take to resolve their issue

Add custom 404 page

---

src/pages/identity.mdx

Adds identity explainer doc to be linked from homepage

Add identity explainer

---

docs/community/contribute.md
docusaurus.config.js

Pointing solely to Discourse for now

Remove links to XMTP Devs chat

---

src/components/BuiltWithXmtp/index.js

Adding a new link for developers to build agents on XMTP on the homepage

Updated eyebrow link on homepage
