xmtp/xmtp-dot-org

src/components/MainContent/index.js

Per https://github.com/xmtp/xmtp-dot-org/issues/142, updating the entire GitHub Discussions, Discord, and Twitter tiles, instead of just the text CTAs.

Link up entire tiles in community section

---

docs/client-sdk/javascript/tutorials/build-key-xmtp-chat-features-in-a-lens-app.md

This PR adds a link to Lenster's `buildConversationKey` method so people can see how we implemented it. I don't think everyone has to implement it this way so I mentioned it specific to Lenster.

Add a link to the `buildConversationKey` helper

---

docusaurus.config.js
src/pages/sdks-and-tools.mdx

- Surfacing the link on the SDK and tools page.
- If we find that people need more obvious access, we can surface the link in the top nav. Trying to keep that area lean for now.

Add link to XMTP status page to "SDK and tools" page

---

docusaurus.config.js

Twitter doesn't properly render URL Preview card for XMTP.org. I changed our config file to include a default image when image scraper crawls through our page
Information found here: https://docusaurus.io/docs/next/api/themes/configuration#meta-image

Added meta image so twitter can render preview card

---

docs/dev-concepts/faq.md
docs/dev-concepts/key-generation-and-usage.md
docs/dev-concepts/signatures.md
docs/dev-concepts/wallets.md
docusaurus.config.js

- Martin provided some insightful feedback that this URL `https://xmtp.org/docs/dev-concepts/signatures` and its 
"Signatures" page title in the left nav may be too generic. He suggested that as-is, just calling it "Signatures" in the left name is so generic that people might think the topic is about signatures inside a message, for example.
- For this reason, we're suggesting that we update the URL to something like `https://xmtp.org/docs/dev-concepts/account-signatures` and the left nav topic name to something like "Account signatures" to help make it clearer that this topic is about how a user needs to use their account keys to provide the signatures XMTP needs to create and enable their XMTP identity.
- Preview here: https://junk-range-possible-git-update-signatures-url-xmtp-labs.verce …

Clarify Signatures page URL and left nav topic title

---

docusaurus.config.js

Ashley suggested that it might be helpful to point people to the XMTP Labs Career page from the footer of xmtp.org.
Preview here: https://junk-range-possible-git-add-careers-link-xmtp-labs.vercel.app/
This is relevant especially based on our recent redirect of xmtp.com to xmtp.org. xmtplabs.com is not showing up in search results yet because there are few to no links to it from web properties. While we work on updating relevant links to point to xmtplabs.com, I agree with Ashely that adding this link to the footer will be helpful to members of the community who might want to contribute by working at XMTP Labs.
Yes, we make a clear separation between .com and .org, but often the Careers .com URL is the one URL surfaced on .org sites.
I put it in the Community column as it seemed to be the …

Add a "Careers at XMTP Labs" link to footer

---

docs/client-sdk/javascript/tutorials/use-content-types.mdx
docs/dev-concepts/invitation-and-message-encryption.md

- Fixes https://github.com/xmtp/xmtp-dot-org/issues/205. Docusaurus doesn't check for broken anchor links. Static site generators I've worked with in the past perform this check so I thought everything was OK! I should have verified. There is an open Docusaurus issue about this missing functionality: https://github.com/facebook/docusaurus/issues/3321
- I will look into possibly using `remark-validate-links` for our site to avoid broken anchor links.
- In the meantime, I've done a manual check and all anchor links are working now.

Fix anchor links

---

vision/roadmap.md

Just for now. Will reassess in Q2 and possibly add the repo back to the Roadmap in the future: https://github.com/xmtp/xmtp-memo-js

Remove xmtp-memo-js SDK from Pre-Preview section on Roadmap

---

docs/client-sdk/javascript/tutorials/use-content-types.mdx
docs/dev-concepts/content-types.mdx

Preview: https://junk-range-possible-git-authorityid-info-xmtp-labs.vercel.app/docs/client-sdk/javascript/tutorials/use-content-types
- While we're here - I also added the seemingly "uncontroversial" "Send plain text messages using the `TextCodec` standard content type" and "Send multiple content types in a message using the `CompositeCodec` standard content type" sections  from this draft: https://www.notion.so/xmtplabs/Encoding-and-decoding-messages-with-XMTP-8fe7fdc460114a1f9eefde7823e476eb?pvs=4 -- too much too soon?
- Full coverage of creating custom content types will come later through Rich's work on the topic.

Clarify that the xmtp.org authorityId is reserved for standard content types

---

docs/client-sdk/javascript/tutorials/use-a-persistent-conversation-cache.md

Provide a tutorial about how to improve conversation load performance by using a persistent conversation cache: [Preview](https://junk-range-possible-git-persistent-convo-cache-xmtp-labs.vercel.app/docs/client-sdk/javascript/tutorials/use-a-persistent-conversation-cache)
Based on:
- https://github.com/xmtp-labs/xmtp-inbox-web/pull/67
- https://github.com/xmtp-labs/xmtp-inbox-web/pull/97

Provide "Use a persistent conversation cache" tutorial

---

docusaurus.config.js

- Also tried to add `gradle`, but not working even if listed as a [Prism language](https://prismjs.com/#supported-languages) supported by Docusaurus. It's just a one-line code block in Kotlin, so not a huge impact.

Add code syntax highlighting for dart, swift, and kotlin

---

docs/dev-concepts/architectural-overview.md
docs/dev-concepts/introduction.md
docs/dev-concepts/start-building.md
docusaurus.config.js
src/components/MainContent/index.js
src/css/tailwind.css

Preview: https://junk-range-possible-git-add-get-started-xmtp-labs.vercel.app/docs/dev-concepts/start-building
- Add "Get started building with XMTP" to Dev concepts
- Add prominent link to it in the top nav. This is where we want people to get started.
- The lightly styled link front and center is the best I could do without design and eng help. =) If we are OK with it as action > perfection, we can request design and eng help with providing a button in the upper right as suggested by Yash in the near future.
- Also linked to the page from the Build with XMTP - Start building button on the home page.
- Once this gets merged, I'll also update each SDK quickstart and README with a link to this doc.

Add "Get started building with XMTP"

---

docs/client-sdk/javascript/reference/classes/Ciphertext.md
docs/client-sdk/javascript/reference/classes/Client.md
docs/client-sdk/javascript/reference/classes/CompositeCodec.md
docs/client-sdk/javascript/reference/classes/ContentTypeId.md
docs/client-sdk/javascript/reference/classes/Conversations.md
docs/client-sdk/javascript/reference/classes/DecodedMessage.md
docs/client-sdk/javascript/reference/classes/EncryptedPersistence.md
docs/client-sdk/javascript/reference/classes/InMemoryKeystore.md
docs/client-sdk/javascript/reference/classes/KeyGeneratorKeystoreProvider.md
docs/client-sdk/javascript/reference/classes/LocalStoragePersistence.md
docs/client-sdk/javascript/reference/classes/NetworkKeystoreProvider.md
docs/client-sdk/javascript/reference/classes/PrefixedPersistence.md
docs/client-sdk/javascript/reference/classes/PrivateKey.md
docs/client-sdk/javascript/reference/classes/PublicKeyBundle.md
docs/client-sdk/javascript/reference/classes/Signature.md
docs/client-sdk/javascript/reference/classes/SignedPublicKey.md
docs/client-sdk/javascript/reference/classes/SignedPublicKeyBundle.md
docs/client-sdk/javascript/reference/classes/StaticKeystoreProvider.md
docs/client-sdk/javascript/reference/classes/Stream.md
docs/client-sdk/javascript/reference/classes/TypingNotificationCodec.md
docs/client-sdk/javascript/reference/classes/_category_.json
docs/client-sdk/javascript/reference/interfaces/ContentCodec.md
docs/client-sdk/javascript/reference/interfaces/Conversation.md
docs/client-sdk/javascript/reference/interfaces/EncodedContent.md
docs/client-sdk/javascript/reference/interfaces/Keystore.md
docs/client-sdk/javascript/reference/interfaces/KeystoreProvider.md
docs/client-sdk/javascript/reference/interfaces/Persistence.md
docs/client-sdk/javascript/reference/interfaces/Signer.md
docs/client-sdk/javascript/reference/interfaces/_category_.json
docs/client-sdk/javascript/reference/modules.md

Update xmtp-js SDK reference docs to reflect v8 functionality.
Preview: https://junk-range-possible-git-v8-ref-docs-xmtp-labs.vercel.app/docs/client-sdk/javascript/reference/classes/Ciphertext

Update xmtp-js ref docs to reflect v8

---

docs/client-sdk/javascript/tutorials/quickstart.md
docs/client-sdk/react/tutorials/quickstart.md
docusaurus.config.js

- Update Documentation -> JavaScript top nav to link to the Quickstart instead of to the Intro concept: [Preview](https://junk-range-possible-git-uxr-feedback-xmtp-labs.vercel.app/)
- Update the JavaScript Quickstart to link to not just the example app repos, but to the apps themselves: [Preview](https://junk-range-possible-git-uxr-feedback-xmtp-labs.vercel.app/docs/client-sdk/javascript/tutorials/quickstart#example-apps-built-with-xmtp-js)
- Update the React SDK Quickstart to link explicitly to the SDK repo: [Preview](https://junk-range-possible-git-uxr-feedback-xmtp-labs.vercel.app/docs/client-sdk/react/tutorials/quickstart)

Address :chefs-kiss: feedback from UXR

---

docs/contribute.md
docs/sdks/dart.md
docs/sdks/js.md
docs/tutorials/lens-multiprofile.md
src/pages/start-building.md

Now that all of the "meat" of the Start building page has been moved into appropriate locations in the documentation, the SBWX page can be a simple list of links to docs.
I'll leave it to Prashant to see if the page continues to serve his needs, even if it is roughly a repeat of the high-level view of the left nav.

Pare down Start building page

---

docs/tutorials/bots.md

We just published v1.0 of this package. For consistency with our other NPM packages, I am putting it under our NPM org (`@xmtp/bot-starter`) instead of what is in the docs `xmtp-bot-starter`.

Fix package name for bot starter

---

src/pages/built-with-xmtp.mdx

During the last update, the page title was lost on the "Built with XMTP" page. This update adds that back in.

Added title and description to the page attributes

---

src/components/Quickstarts/index.md

They are swapped, `Dart` should link to flutter and `Kotlin` should link to android

Fix kotlin and dart Quickstart links

---

docs/build/group-chats.md

The previous instructions were for developers to clone the repo to get access to group chat. This is frustrating, because developers would then have to build it themselves and use NPM link. A more straightforward option exists, which is to use the `beta` tag in NPM which has access to the group chat features as normal NPM packages.

Update group chat instructions

---

src/components/Tutorial/index.js

Refreshes page when component mounts and unmounts. This is a required workaround due to side effects of setting cross-origin isolated headers in only one route. While it is not ideal, it seemed to be the best option given tradeoffs of alternatives.

Add reload logic for tutorial

---

docs/build/authentication.md
docs/build/conversations.md
docs/build/get-started.md
docs/build/local-first.md
docs/build/messages/messages.md
docs/build/messages/reaction.mdx
docs/build/messages/read-receipt.mdx
docs/build/messages/remote-attachment.mdx
docs/build/messages/reply.mdx
docs/build/notifications.md
docs/build/streams.md
docs/tutorials/broadcast.md

- Some tabs weren't automatically switching to currently selected language - just a config thing.
- Put tabs in consistent order - web (JS, React) and then mobile (Kotlin, Swift, Dart, RN) in order of popularity per repo stars and release status
- Provided all tabs even if no code sample is available, applicable, or the feature hasn't been implemented for the SDK yet. I've inventoried the missing code samples and we can gather them. I think providing all of the tabs in every case, with an explanation when no code sample is available, is helpful for consistency and orientation.

Tab hygiene

---

docs/build/messages/messages.md
docs/build/messages/read-receipt.mdx
docs/build/messages/remote-attachment.mdx
docs/build/messages/reply.mdx

In this PR:
* Added options for the `useMessages` hook
* Updated read receipts docs to reflect recent change to the content type's schema
* Fixed `sendMessage` call for remote attachment content type
* Updated reply docs for more consistency with other content types

Update some React docs

---

docs/concepts/_category_.json
docs/interactive-tutorial.md
docs/tutorials/_category_.json
docs/use-cases/_category_.json

Preview: https://junk-range-possible-git-move-use-cases-xmtp-labs.vercel.app/docs/introduction
Fabri and I discussed that "Use cases" are already very accessible from the top nav. It would be great to move "Use cases" to the bottom of the left nav to allow "Tutorials" and "Concepts" to move up in the nav. This PR does that.

Move "Use cases" section to bottom of Documentation left nav

---

docs/build/messages/read-receipt.mdx

Incremental update to guidance for read receipt content type usage based on already approved content from this merged PR: https://github.com/xmtp/xmtp-js-content-types/pull/40/files#diff-2e3b332a470b04c0ae2f86d94a52edb8d5f2ac7e346a84b44850421a502ac94c

Update read receipt content type status and usage info

---

docs/build/user-consent.md

- Adds references to privacy and encryption.
- Clarifies that it is not the user's blockchain account that has one of the three values.

reference privacy and encryption in description of consent lists

---

docusaurus.config.js
src/css/tailwind.css
src/pages/index.js

The Flickety carousel was hitting some race conditions when the Home component rendered before the script was finished loading. This PR adds a check to make sure the class exists before a new instance gets instantiated, and then updated some CSS so the fallback scenario looks as expected when Flickity is not defined (just stays on static image and doesn't rotate the carousel). 
While at it removed the cross-origin tags in the scripts as they are no longer needed.

Added Flickety check and fallback

---

docs/build/messages/remote-attachment.mdx

Hi team,
Docs update:
- Now the React SDK tab match the Javascript one for multi-step uploading of remote content types
- The left navigation label `Attachment` have also been updated to `Remote Attachment`
- Added `ContentTypeId` to help with comparing content types.
A few questions:
- Currently, `ContentTypeId` works with React SDK but not with JS SDK. Is this the best method for type comparison?
- Are there any specific hooks related to remote attachments that we should mention in the documentation?
- For the contentFallback, the default message "This app doesn’t support attachments" is functional in React SDK but not in JS SDK. Any thoughts?
cc. @rygine 🙏🏻
[URL Preview](https://junk-range-possible-git-cthooks-xmtp-labs.vercel.app/docs/build/messages/remote-attachment)
Let me know if …

Remote Attachments React SDK

---

docs/build/authentication.md

Previously in the documentation snippet, the process for saving keys and creating clients was combined together. However, the saving keys snippet for the flutter tab was empty. With this update, the client creation process is now explained separately and a corresponding snippet for saving keys has been added.
Also, added in the snippet setting the `dev` network instead of the default `local`.
```
var api = xmtp.Api.create(host: 'dev.xmtp.network', isSecure: true)
var client = await Client.createFromWallet(api, wallet);
```
```
var api = xmtp.Api.create();
var client = await Client.createFromWallet(api, wallet);
await mySecureStorage.save(client.keys.writeToBuffer());
//The second time a user launches the app they should call `createFromKeys` using the stored `keys` from their previous …
```

Flutter Save Keys Snippet

---

README.md
blog/introducing-the-xmtp-litepaper.md
docs/build/messages/reaction.mdx
docs/build/messages/reply.mdx
docs/concepts/content-types.md
docs/concepts/xips.mdx
docs/contribute.md
docs/faq.md
docusaurus.config.js
src/components/Feedback/index.js
src/components/MainContent/index.js
src/pages/privacy.mdx
src/pages/start-building.md
src/pages/terms.mdx

Some GH Discussions links remain because they point to active discussions that haven't been migrated yet. Will update links once migration is complete.

Point GH Discussions links to Discourse

---

docs/build/get-started/overview.md
docs/faq.md
src/css/tailwind.css

This PR adds three solutions to address the 'Buffer not found' issue in React applications, particularly for projects created with Create React App (CRA). The update includes methods using CRACO, React-App-Rewired, and the Eject option, providing users with different levels of customization for webpack configuration.
1. **CRACO**: Instructions and code for setting up CRACO to modify webpack config without ejecting.
2. **React-App-Rewired**: Guide and configuration details for using `react-app-rewired`.
3. **Eject Method**: Steps for ejecting from CRA and manually adjusting `webpack.config.js`.
- [Preview](https://junk-range-possible-git-bufferupdate-xmtp-labs.vercel.app/docs/faq#why-my-app-is-failing-saying-buffer-is-not-found)

Add Solutions for 'Buffer Not Found' Issue in React

---

docs/build/messages/messages.md
docs/build/messages/reaction.mdx
docs/build/messages/read-receipt.mdx
docs/build/messages/remote-attachment.mdx
docs/build/messages/reply.mdx
docs/tutorials/custom-ct.mdx

This PR updates documentation related to content types based on the release [v1.21.0](https://github.com/xmtp/xmtp-react-native/releases/tag/v1.21.0) of the RN SDK
XMTP used to register supported codecs for you by default. Now you must register all codecs you’d like to support manually on client create
- [RemoteAttachments](https://junk-range-possible-git-rnct-xmtp-labs.vercel.app/docs/build/messages/remote-attachment)
- [Reply](https://junk-range-possible-git-rnct-xmtp-labs.vercel.app/docs/build/messages/reply)
- [ReadReceipt](https://junk-range-possible-git-rnct-xmtp-labs.vercel.app/docs/build/messages/read-receipt)
- [Reaction](https://junk-range-possible-git-rnct-xmtp-labs.vercel.app/docs/build/messages/reaction)
React Native now supports custom codecs, enabling you to send any type …

React Native Content Type Updates

---

docs/build/authentication.md
docs/build/conversations.md
docs/build/get-started/overview.md
docs/build/messages/reply.mdx
docs/developer-quickstart.md
docs/tutorials/broadcast.md
docs/tutorials/cli.md
docs/tutorials/custom-ct.mdx
src/components/FeedbackWidget/utils.js

All reference Snippets to Client creation now mention `signer` instead of `wallet` 
Eg:
Before:
`const client = await Client.create(wallet,/**/)`
After:
`const client = await Client.create(signer,/**/)`

Updated `Signer` references

---

docs/build/get-started/references.md

Update `https://xmtp.github.io/xmtp-ios/documentation/xmtp` with new one `https://xmtp.github.io/xmtp-ios/` based on the [PR](https://github.com/xmtp/xmtp-ios/pull/207) fixing the generated docs.
- [Preview Docs](https://xmtp.github.io/xmtp-ios/)

URL IOS Docs update

---

docs/build/user-consent.md
docs/concepts/architectural-overview.md
docs/faq.md

Updated some snippets and features based on the latest of [JS](https://github.com/xmtp/xmtp-js/releases/tag/v11.3.0) and [React](https://github.com/xmtp/xmtp-web/releases/tag/%40xmtp%2Freact-sdk%403.1.0) 
- [Preview](https://junk-range-possible-git-consentrelease-xmtp-labs.vercel.app/docs/build/user-consent)

Portable Consent Update

---

docs/concepts/architectural-overview.md
docs/faq.md
docs/tutorials/debug-and-test.md

Added a link to the Request Rate Limit Increase form to the Rate-limiting FAQ section.
[Preview here](https://junk-range-possible-git-rate-limit-details-xmtp-labs.vercel.app/docs/faq#what-are-the-api-rate-limits)

Add rate limit increase form link

---

docs/build/messages/messages.md
docs/faq.md

Per feedback, let's add maximum message size info to the docs. Max message size is 1MB.
- [FAQ preview link ](https://junk-range-possible-git-message-size-xmtp-labs.vercel.app/docs/faq#does-xmtp-have-a-maximum-message-size)
- [Send messages preview link](https://junk-range-possible-git-message-size-xmtp-labs.vercel.app/docs/build/messages/#send-messages)

Add max message size to docs

---

docs/faq.md

Per @fabriguespe's suggestion, let's also provide the max size for the attachment content type - same as for a message - up to 1MB.
[Preview link](https://junk-range-possible-git-attachment-max-size-xmtp-labs.vercel.app/docs/faq#does-xmtp-support-message-attachments)

Add max attachment size

---

docs/build/messages/messages.md
docs/build/messages/reaction.mdx
docs/build/messages/read-receipt.mdx
docs/build/messages/remote-attachment.mdx
docs/build/messages/reply.mdx

This PR explains how to recognize un supported content types and display a fallback instead.
- [Preview](https://junk-range-possible-git-fallbackv1-xmtp-labs.vercel.app/docs/build/messages/#handle-unsupported-content-types)

Handle unsupported content types

---

src/pages/code-of-conduct.md

The XMTP community spaces have evolved over 2 years, thus the code of conduct need a refresh.
[Preview link](https://junk-range-possible-git-codeofconduct-v2-xmtp-labs.vercel.app/code-of-conduct)

Update code of conduct

---

docs/tutorials/transaction-frames.md

Most Frames use Base mainnet to address high fees, rather than restricting themselves to L1 testnet.

Remove reference to mainnet fees

---

docs/build/broadcast.md
docs/build/group-chat.md
docs/build/spam.md

Fix anchor link and make title MLS-specific

---

docs/build/subscribe.md

[Preview link](https://junk-range-possible-git-brand-subscribe-xmtp-labs.vercel.app/docs/build/subscribe): See Best Practice callout

Add best practice for enabling granular subscriptions per content source

---

docusaurus.config.js

- Search is no longer necessary as the docs live at https://docs.xmtp.org/
- Including search implies the site contains more content than it does - leading people to dissatisfying or misleading results.

Remove search

---

src/components/NotifiCaseStudy/index.js

- Remove "Learn more" link from top of page
- Replace with "Reach out" link at bottom of page
- See [preview here](https://junk-range-possible-git-notifi-link-ephemerahq.vercel.app/notifi-case-study)

Update CTA for Notifi case study
